# Dependencies
# markdown:         kramdown
# highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            'Seminar hub'
description:      'Coordinating joint international seminars in mathematical sciences'
location:         'Based at Yau MSC, Beijing'
url:              https://w-donovan.github.io
baseurl:          /


exclude: [ "README.md" ]