# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Joint international math seminars'
tagline:          ''
description:      'Organized between Yau MSC, Tsinghua University, and international partners'
location:         ''
url:              https://w-donovan.github.io
baseurl:          /


exclude: [ "README.md" ]