# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Test'
tagline:          'Testing'
description:      'Tested'
location:         ''
url:              https://w-donovan.github.io
baseurl:          /


exclude: [ "README.md" ]