# Dependencies
# markdown:         kramdown
# highlighter:      rouge

# Permalinks
# permalink:        pretty

# Site location
url:              https://w-donovan.github.io
baseurl:          /

# Description text
title:            'Yau MSC events hub'
description:      'Coordinating joint international events in mathematical sciences'
location:         'Based at Yau MSC, Beijing'


# Parameters
contact:           'Name'
contactaddr:       'xxx@mail.tsinghua.edu.cn'
calendarurl:       'https://teamup.com/ks58v9swjiomt7ii2k'

exclude: [ "README.md" ]
