# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Joint seminars'
description:      'Between YMSC in Beijing and international'
tagline:          'Organized between Yau MSC, Tsinghua University, and international partners'
location:         ''
url:              https://w-donovan.github.io
baseurl:          /


exclude: [ "README.md" ]