# Dependencies
# markdown:         kramdown
# highlighter:      rouge

# Permalinks
# permalink:        pretty

# Site location
url:              https://yau-msc-events.github.io
baseurl:          /

# Description text
title:            'Yau MSC events hub'
description:      'Coordinating joint international events in mathematical sciences'
location:         'Based at [Yau MSC](https://ymsc.tsinghua.edu.cn/), Beijing'


# Parameters
contact:           'Will Donovan'
contactaddr:       'donovan@mail.tsinghua.edu.cn '
calendarurl:       'https://teamup.com/ks58v9swjiomt7ii2k'

exclude: [ "README.md" ]
